baseURL = 'https://teaching.wence.uk/phys52015/'
DefaultContentLanguage = 'en'
title = 'PHYS52015 â€“ Introduction to HPC'

staticDir = ['static']
disablePathToLower = false
enableGitInfo = true
enableRobotsTXT = false

theme = 'book'

disableKinds = ['taxonomy', 'taxonomyTerm']
# Needed for katex shortcodes
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokailight'
    tabWidth = 8
    
[params]
BookSection = '/'
BookSearch = false
BookComments = false
BookToc = false
BookRepo = 'https://github.com/wenceorg/phys52015'
ModulePage = 'https://www.dur.ac.uk/postgraduate.modules/module_description/?year=2020&module_code=PHYS52015'
BookEditPath = 'edit/main/site/content'
ImageDir = 'images'
CopyRight = '&copy; 2020-- [Lawrence Mitchell](mailto:lawrence@wence.uk), [Christian Arnold](https://www.dur.ac.uk/physics/staff/profiles/?mode=staff&id=16712) & [Durham University](https://www.dur.ac.uk/).'
