name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  autobuild-dispatch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a set of commands using the runners shell
    - name: Post dispatch
      run: |
        curl -X POST \
             -H "Accept: application/vnd.github.v3+json" \
             -H "Authorization: token ${{ secrets.AUTOBUILD_REPO_PAT }}" \
             https://api.github.com/repos/wenceorg/autobuild-teaching-pages/dispatches \
             -d '{"event_type": "web-update",
                  "client_payload":
                    {"ref": "${{ github.sha }}",
                     "repository": "${{ github.repository }}",
                     "repository_name": "${{ github.event.repository.name}}" }}'
